/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as R403RouteImport } from './routes/403'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SettingsIndexRouteImport } from './routes/settings/index'
import { Route as RunsIndexRouteImport } from './routes/runs/index'
import { Route as PromptsIndexRouteImport } from './routes/prompts/index'
import { Route as HooksIndexRouteImport } from './routes/hooks/index'
import { Route as ElementsIndexRouteImport } from './routes/elements/index'
import { Route as BooksIndexRouteImport } from './routes/books/index'
import { Route as BatchesIndexRouteImport } from './routes/batches/index'
import { Route as AuditIndexRouteImport } from './routes/audit/index'
import { Route as AntiPatternsIndexRouteImport } from './routes/anti-patterns/index'
import { Route as RunsIdRouteImport } from './routes/runs/$id'
import { Route as PromptsSlugRouteImport } from './routes/prompts/$slug'
import { Route as ElementsIdRouteImport } from './routes/elements/$id'
import { Route as BooksBookIdRouteImport } from './routes/books/$bookId'
import { Route as BatchesIdRouteImport } from './routes/batches/$id'
import { Route as StylesSamplesIndexRouteImport } from './routes/styles/samples/index'
import { Route as BooksBookIdIndexRouteImport } from './routes/books/$bookId.index'
import { Route as BooksBookIdThreadsRouteImport } from './routes/books/$bookId.threads'
import { Route as BooksBookIdFilesRouteImport } from './routes/books/$bookId.files'
import { Route as BooksBookIdDesignRouteImport } from './routes/books/$bookId.design'
import { Route as BooksBookIdChatRouteImport } from './routes/books/$bookId.chat'
import { Route as BooksBookIdFilesIndexRouteImport } from './routes/books/$bookId.files.index'
import { Route as BooksBookIdScoutIdxRouteImport } from './routes/books/$bookId.scout.$idx'
import { Route as BooksBookIdFilesKindSplatRouteImport } from './routes/books/$bookId.files.$kind.$'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const R403Route = R403RouteImport.update({
  id: '/403',
  path: '/403',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsIndexRoute = SettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIndexRoute = RunsIndexRouteImport.update({
  id: '/runs/',
  path: '/runs/',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsIndexRoute = PromptsIndexRouteImport.update({
  id: '/prompts/',
  path: '/prompts/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksIndexRoute = HooksIndexRouteImport.update({
  id: '/hooks/',
  path: '/hooks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsIndexRoute = ElementsIndexRouteImport.update({
  id: '/elements/',
  path: '/elements/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksIndexRoute = BooksIndexRouteImport.update({
  id: '/books/',
  path: '/books/',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIndexRoute = BatchesIndexRouteImport.update({
  id: '/batches/',
  path: '/batches/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditIndexRoute = AuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => rootRouteImport,
} as any)
const AntiPatternsIndexRoute = AntiPatternsIndexRouteImport.update({
  id: '/anti-patterns/',
  path: '/anti-patterns/',
  getParentRoute: () => rootRouteImport,
} as any)
const RunsIdRoute = RunsIdRouteImport.update({
  id: '/runs/$id',
  path: '/runs/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PromptsSlugRoute = PromptsSlugRouteImport.update({
  id: '/prompts/$slug',
  path: '/prompts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsIdRoute = ElementsIdRouteImport.update({
  id: '/elements/$id',
  path: '/elements/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdRoute = BooksBookIdRouteImport.update({
  id: '/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchesIdRoute = BatchesIdRouteImport.update({
  id: '/batches/$id',
  path: '/batches/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const StylesSamplesIndexRoute = StylesSamplesIndexRouteImport.update({
  id: '/styles/samples/',
  path: '/styles/samples/',
  getParentRoute: () => rootRouteImport,
} as any)
const BooksBookIdIndexRoute = BooksBookIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdThreadsRoute = BooksBookIdThreadsRouteImport.update({
  id: '/threads',
  path: '/threads',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdFilesRoute = BooksBookIdFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdDesignRoute = BooksBookIdDesignRouteImport.update({
  id: '/design',
  path: '/design',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdChatRoute = BooksBookIdChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdFilesIndexRoute = BooksBookIdFilesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BooksBookIdFilesRoute,
} as any)
const BooksBookIdScoutIdxRoute = BooksBookIdScoutIdxRouteImport.update({
  id: '/scout/$idx',
  path: '/scout/$idx',
  getParentRoute: () => BooksBookIdRoute,
} as any)
const BooksBookIdFilesKindSplatRoute =
  BooksBookIdFilesKindSplatRouteImport.update({
    id: '/$kind/$',
    path: '/$kind/$',
    getParentRoute: () => BooksBookIdFilesRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/batches/$id': typeof BatchesIdRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/elements/$id': typeof ElementsIdRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/runs/$id': typeof RunsIdRoute
  '/anti-patterns/': typeof AntiPatternsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/batches/': typeof BatchesIndexRoute
  '/books/': typeof BooksIndexRoute
  '/elements/': typeof ElementsIndexRoute
  '/hooks/': typeof HooksIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/books/$bookId/chat': typeof BooksBookIdChatRoute
  '/books/$bookId/design': typeof BooksBookIdDesignRoute
  '/books/$bookId/files': typeof BooksBookIdFilesRouteWithChildren
  '/books/$bookId/threads': typeof BooksBookIdThreadsRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/styles/samples/': typeof StylesSamplesIndexRoute
  '/books/$bookId/scout/$idx': typeof BooksBookIdScoutIdxRoute
  '/books/$bookId/files/': typeof BooksBookIdFilesIndexRoute
  '/books/$bookId/files/$kind/$': typeof BooksBookIdFilesKindSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/batches/$id': typeof BatchesIdRoute
  '/elements/$id': typeof ElementsIdRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/runs/$id': typeof RunsIdRoute
  '/anti-patterns': typeof AntiPatternsIndexRoute
  '/audit': typeof AuditIndexRoute
  '/batches': typeof BatchesIndexRoute
  '/books': typeof BooksIndexRoute
  '/elements': typeof ElementsIndexRoute
  '/hooks': typeof HooksIndexRoute
  '/prompts': typeof PromptsIndexRoute
  '/runs': typeof RunsIndexRoute
  '/settings': typeof SettingsIndexRoute
  '/books/$bookId/chat': typeof BooksBookIdChatRoute
  '/books/$bookId/design': typeof BooksBookIdDesignRoute
  '/books/$bookId/threads': typeof BooksBookIdThreadsRoute
  '/books/$bookId': typeof BooksBookIdIndexRoute
  '/styles/samples': typeof StylesSamplesIndexRoute
  '/books/$bookId/scout/$idx': typeof BooksBookIdScoutIdxRoute
  '/books/$bookId/files': typeof BooksBookIdFilesIndexRoute
  '/books/$bookId/files/$kind/$': typeof BooksBookIdFilesKindSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/403': typeof R403Route
  '/login': typeof LoginRoute
  '/batches/$id': typeof BatchesIdRoute
  '/books/$bookId': typeof BooksBookIdRouteWithChildren
  '/elements/$id': typeof ElementsIdRoute
  '/prompts/$slug': typeof PromptsSlugRoute
  '/runs/$id': typeof RunsIdRoute
  '/anti-patterns/': typeof AntiPatternsIndexRoute
  '/audit/': typeof AuditIndexRoute
  '/batches/': typeof BatchesIndexRoute
  '/books/': typeof BooksIndexRoute
  '/elements/': typeof ElementsIndexRoute
  '/hooks/': typeof HooksIndexRoute
  '/prompts/': typeof PromptsIndexRoute
  '/runs/': typeof RunsIndexRoute
  '/settings/': typeof SettingsIndexRoute
  '/books/$bookId/chat': typeof BooksBookIdChatRoute
  '/books/$bookId/design': typeof BooksBookIdDesignRoute
  '/books/$bookId/files': typeof BooksBookIdFilesRouteWithChildren
  '/books/$bookId/threads': typeof BooksBookIdThreadsRoute
  '/books/$bookId/': typeof BooksBookIdIndexRoute
  '/styles/samples/': typeof StylesSamplesIndexRoute
  '/books/$bookId/scout/$idx': typeof BooksBookIdScoutIdxRoute
  '/books/$bookId/files/': typeof BooksBookIdFilesIndexRoute
  '/books/$bookId/files/$kind/$': typeof BooksBookIdFilesKindSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/403'
    | '/login'
    | '/batches/$id'
    | '/books/$bookId'
    | '/elements/$id'
    | '/prompts/$slug'
    | '/runs/$id'
    | '/anti-patterns/'
    | '/audit/'
    | '/batches/'
    | '/books/'
    | '/elements/'
    | '/hooks/'
    | '/prompts/'
    | '/runs/'
    | '/settings/'
    | '/books/$bookId/chat'
    | '/books/$bookId/design'
    | '/books/$bookId/files'
    | '/books/$bookId/threads'
    | '/books/$bookId/'
    | '/styles/samples/'
    | '/books/$bookId/scout/$idx'
    | '/books/$bookId/files/'
    | '/books/$bookId/files/$kind/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/403'
    | '/login'
    | '/batches/$id'
    | '/elements/$id'
    | '/prompts/$slug'
    | '/runs/$id'
    | '/anti-patterns'
    | '/audit'
    | '/batches'
    | '/books'
    | '/elements'
    | '/hooks'
    | '/prompts'
    | '/runs'
    | '/settings'
    | '/books/$bookId/chat'
    | '/books/$bookId/design'
    | '/books/$bookId/threads'
    | '/books/$bookId'
    | '/styles/samples'
    | '/books/$bookId/scout/$idx'
    | '/books/$bookId/files'
    | '/books/$bookId/files/$kind/$'
  id:
    | '__root__'
    | '/'
    | '/403'
    | '/login'
    | '/batches/$id'
    | '/books/$bookId'
    | '/elements/$id'
    | '/prompts/$slug'
    | '/runs/$id'
    | '/anti-patterns/'
    | '/audit/'
    | '/batches/'
    | '/books/'
    | '/elements/'
    | '/hooks/'
    | '/prompts/'
    | '/runs/'
    | '/settings/'
    | '/books/$bookId/chat'
    | '/books/$bookId/design'
    | '/books/$bookId/files'
    | '/books/$bookId/threads'
    | '/books/$bookId/'
    | '/styles/samples/'
    | '/books/$bookId/scout/$idx'
    | '/books/$bookId/files/'
    | '/books/$bookId/files/$kind/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  R403Route: typeof R403Route
  LoginRoute: typeof LoginRoute
  BatchesIdRoute: typeof BatchesIdRoute
  BooksBookIdRoute: typeof BooksBookIdRouteWithChildren
  ElementsIdRoute: typeof ElementsIdRoute
  PromptsSlugRoute: typeof PromptsSlugRoute
  RunsIdRoute: typeof RunsIdRoute
  AntiPatternsIndexRoute: typeof AntiPatternsIndexRoute
  AuditIndexRoute: typeof AuditIndexRoute
  BatchesIndexRoute: typeof BatchesIndexRoute
  BooksIndexRoute: typeof BooksIndexRoute
  ElementsIndexRoute: typeof ElementsIndexRoute
  HooksIndexRoute: typeof HooksIndexRoute
  PromptsIndexRoute: typeof PromptsIndexRoute
  RunsIndexRoute: typeof RunsIndexRoute
  SettingsIndexRoute: typeof SettingsIndexRoute
  StylesSamplesIndexRoute: typeof StylesSamplesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/403': {
      id: '/403'
      path: '/403'
      fullPath: '/403'
      preLoaderRoute: typeof R403RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/': {
      id: '/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof SettingsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/': {
      id: '/runs/'
      path: '/runs'
      fullPath: '/runs/'
      preLoaderRoute: typeof RunsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/': {
      id: '/prompts/'
      path: '/prompts'
      fullPath: '/prompts/'
      preLoaderRoute: typeof PromptsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/': {
      id: '/hooks/'
      path: '/hooks'
      fullPath: '/hooks/'
      preLoaderRoute: typeof HooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements/': {
      id: '/elements/'
      path: '/elements'
      fullPath: '/elements/'
      preLoaderRoute: typeof ElementsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/': {
      id: '/books/'
      path: '/books'
      fullPath: '/books/'
      preLoaderRoute: typeof BooksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/': {
      id: '/batches/'
      path: '/batches'
      fullPath: '/batches/'
      preLoaderRoute: typeof BatchesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit/': {
      id: '/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuditIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anti-patterns/': {
      id: '/anti-patterns/'
      path: '/anti-patterns'
      fullPath: '/anti-patterns/'
      preLoaderRoute: typeof AntiPatternsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/runs/$id': {
      id: '/runs/$id'
      path: '/runs/$id'
      fullPath: '/runs/$id'
      preLoaderRoute: typeof RunsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prompts/$slug': {
      id: '/prompts/$slug'
      path: '/prompts/$slug'
      fullPath: '/prompts/$slug'
      preLoaderRoute: typeof PromptsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements/$id': {
      id: '/elements/$id'
      path: '/elements/$id'
      fullPath: '/elements/$id'
      preLoaderRoute: typeof ElementsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId': {
      id: '/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof BooksBookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batches/$id': {
      id: '/batches/$id'
      path: '/batches/$id'
      fullPath: '/batches/$id'
      preLoaderRoute: typeof BatchesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/styles/samples/': {
      id: '/styles/samples/'
      path: '/styles/samples'
      fullPath: '/styles/samples/'
      preLoaderRoute: typeof StylesSamplesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/books/$bookId/': {
      id: '/books/$bookId/'
      path: '/'
      fullPath: '/books/$bookId/'
      preLoaderRoute: typeof BooksBookIdIndexRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/threads': {
      id: '/books/$bookId/threads'
      path: '/threads'
      fullPath: '/books/$bookId/threads'
      preLoaderRoute: typeof BooksBookIdThreadsRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/files': {
      id: '/books/$bookId/files'
      path: '/files'
      fullPath: '/books/$bookId/files'
      preLoaderRoute: typeof BooksBookIdFilesRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/design': {
      id: '/books/$bookId/design'
      path: '/design'
      fullPath: '/books/$bookId/design'
      preLoaderRoute: typeof BooksBookIdDesignRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/chat': {
      id: '/books/$bookId/chat'
      path: '/chat'
      fullPath: '/books/$bookId/chat'
      preLoaderRoute: typeof BooksBookIdChatRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/files/': {
      id: '/books/$bookId/files/'
      path: '/'
      fullPath: '/books/$bookId/files/'
      preLoaderRoute: typeof BooksBookIdFilesIndexRouteImport
      parentRoute: typeof BooksBookIdFilesRoute
    }
    '/books/$bookId/scout/$idx': {
      id: '/books/$bookId/scout/$idx'
      path: '/scout/$idx'
      fullPath: '/books/$bookId/scout/$idx'
      preLoaderRoute: typeof BooksBookIdScoutIdxRouteImport
      parentRoute: typeof BooksBookIdRoute
    }
    '/books/$bookId/files/$kind/$': {
      id: '/books/$bookId/files/$kind/$'
      path: '/$kind/$'
      fullPath: '/books/$bookId/files/$kind/$'
      preLoaderRoute: typeof BooksBookIdFilesKindSplatRouteImport
      parentRoute: typeof BooksBookIdFilesRoute
    }
  }
}

interface BooksBookIdFilesRouteChildren {
  BooksBookIdFilesIndexRoute: typeof BooksBookIdFilesIndexRoute
  BooksBookIdFilesKindSplatRoute: typeof BooksBookIdFilesKindSplatRoute
}

const BooksBookIdFilesRouteChildren: BooksBookIdFilesRouteChildren = {
  BooksBookIdFilesIndexRoute: BooksBookIdFilesIndexRoute,
  BooksBookIdFilesKindSplatRoute: BooksBookIdFilesKindSplatRoute,
}

const BooksBookIdFilesRouteWithChildren =
  BooksBookIdFilesRoute._addFileChildren(BooksBookIdFilesRouteChildren)

interface BooksBookIdRouteChildren {
  BooksBookIdChatRoute: typeof BooksBookIdChatRoute
  BooksBookIdDesignRoute: typeof BooksBookIdDesignRoute
  BooksBookIdFilesRoute: typeof BooksBookIdFilesRouteWithChildren
  BooksBookIdThreadsRoute: typeof BooksBookIdThreadsRoute
  BooksBookIdIndexRoute: typeof BooksBookIdIndexRoute
  BooksBookIdScoutIdxRoute: typeof BooksBookIdScoutIdxRoute
}

const BooksBookIdRouteChildren: BooksBookIdRouteChildren = {
  BooksBookIdChatRoute: BooksBookIdChatRoute,
  BooksBookIdDesignRoute: BooksBookIdDesignRoute,
  BooksBookIdFilesRoute: BooksBookIdFilesRouteWithChildren,
  BooksBookIdThreadsRoute: BooksBookIdThreadsRoute,
  BooksBookIdIndexRoute: BooksBookIdIndexRoute,
  BooksBookIdScoutIdxRoute: BooksBookIdScoutIdxRoute,
}

const BooksBookIdRouteWithChildren = BooksBookIdRoute._addFileChildren(
  BooksBookIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  R403Route: R403Route,
  LoginRoute: LoginRoute,
  BatchesIdRoute: BatchesIdRoute,
  BooksBookIdRoute: BooksBookIdRouteWithChildren,
  ElementsIdRoute: ElementsIdRoute,
  PromptsSlugRoute: PromptsSlugRoute,
  RunsIdRoute: RunsIdRoute,
  AntiPatternsIndexRoute: AntiPatternsIndexRoute,
  AuditIndexRoute: AuditIndexRoute,
  BatchesIndexRoute: BatchesIndexRoute,
  BooksIndexRoute: BooksIndexRoute,
  ElementsIndexRoute: ElementsIndexRoute,
  HooksIndexRoute: HooksIndexRoute,
  PromptsIndexRoute: PromptsIndexRoute,
  RunsIndexRoute: RunsIndexRoute,
  SettingsIndexRoute: SettingsIndexRoute,
  StylesSamplesIndexRoute: StylesSamplesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
